"""Initial schema

Revision ID: 32499e6ae2b6
Revises: 
Create Date: 2025-08-27 12:45:43.839275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32499e6ae2b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('RoleID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('RoleName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('RoleID'),
    sa.UniqueConstraint('RoleName')
    )
    op.create_table('users',
    sa.Column('UserID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('Mobile', sa.String(length=15), nullable=False),
    sa.Column('Salt', sa.String(length=64), nullable=False),
    sa.Column('PasswordHash', sa.String(length=128), nullable=False),
    sa.Column('Role', sa.Integer(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Role'], ['roles.RoleID'], ),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Mobile')
    )
    op.create_table('audit_logs',
    sa.Column('LogID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Action', sa.String(length=255), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('LogID')
    )
    op.create_table('service_requests',
    sa.Column('RequestID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('ServiceType', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('FeeAmount', sa.Float(), nullable=False),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('RequestID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_requests')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
